### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by YoungerMax** [abdowns/openglboilerplate#2]
The codebase is ugly right now:
- full of commented out code
- looks nasty
- no consistent formatting

clean it up!

**Comment by abdowns** [comment]
I'll get on this

**Comment by abdowns** [comment]
@YoungerMax 
Sat 25 Jun, 00:19

Commit https://github.com/abdowns/openglboilerplate/commit/bb25e14360c6f8910e3f66a63476f7df721dfff3

### Changes
- Made ResourceHandler static
- Put more of the code from main.cpp into program class
- General cleaning

### Error
I had to make resourcehandler static, but in doing so, [this](https://gist.github.com/abdowns/97f61f0a53fcfd439f2e5e98057a0ed5) error came up again. We just need to push through debugging it rather than writing bad code to fix it. Work also has to be done to the renderer class because it should not be a pointer as far as I'm concerened. Once all this gets fixed everything will be much better.

**Comment by YoungerMax** [comment]
@abdowns 
I fixed many of the linking errors you identified.

Before:
```
/usr/bin/ld: /tmp/ccOwE8Pp.o: in function `util::calcTime(float*, float*)':
main.cpp:(.text+0x0): multiple definition of `util::calcTime(float*, float*)'; /tmp/cc85frVB.o:input.cpp:(.text+0x0): first defined here
/usr/bin/ld: /tmp/cccag0Q8.o: warning: relocation against `_ZN15ResourceManager9shaderMapB5cxx11E' in read-only section `.text'
/usr/bin/ld: /tmp/cccag0Q8.o: in function `ResourceManager::allocateShader(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
resources.cpp:(.text+0xc0): undefined reference to `ResourceManager::shaderMap[abi:cxx11]'
/usr/bin/ld: resources.cpp:(.text+0x13e): undefined reference to `ResourceManager::shaderMap[abi:cxx11]'
/usr/bin/ld: resources.cpp:(.text+0x170): undefined reference to `ResourceManager::shaderMap[abi:cxx11]'
/usr/bin/ld: /tmp/cccag0Q8.o: in function `ResourceManager::getShader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
resources.cpp:(.text+0x23a): undefined reference to `ResourceManager::shaderMap[abi:cxx11]'
/usr/bin/ld: /tmp/cccag0Q8.o: in function `ResourceManager::Clear()':
resources.cpp:(.text+0x6ca): undefined reference to `ResourceManager::shaderMap[abi:cxx11]'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make: *** [Makefile:4: build] Error 1
```

After:
```
/usr/bin/ld: /tmp/ccOzH9Qp.o: in function `util::calcTime(float*, float*)':
main.cpp:(.text+0x0): multiple definition of `util::calcTime(float*, float*)'; /tmp/ccDFjQXq.o:input.cpp:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:4: build] Error 1
```

I pushed these changes to `dev` and I am currently working on fixing the last of those errors. My guess with this last one is that `utils.hpp` is being included twice because there are multiple definitions of `util::calcTime(float*, float*)`

**Comment by abdowns** [comment]
I think I know the source of the issue and I'll be working on a fix today
